#ifndef _XY_SUBSYS_REQ_
#define _XY_SUBSYS_REQ_
#include "TypeDefine.h"
#include "xy_nbiot_msg_define.h"

enum
{
    XY_SUBSYS_CAIL_BASE = XY_SUBSYS_CAIL_REQ << 16,
    MSG_SHOW_NAME(XY_SUBSYS_CALI_START_REQ, nullStruct),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_STOP_REQ, nullStruct),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_AFC_REQ, XY_SUBSYS_CALI_APC_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_APC_REQ, XY_SUBSYS_CALI_APC_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_AGC_REQ, XY_SUBSYS_CALI_APC_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_DC_REQ, XY_SUBSYS_CALI_DC_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_IMAGE_REQ, XY_SUBSYS_CALI_IMAGE_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_DCCAL_REQ, XY_SUBSYS_CALI_DCCAL_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_CHECK_REQ, nullStruct),
    MSG_SHOW_NAME(XY_SUBSYS_CALI_SWTICHMS_REQ, XY_SUBSYS_CALI_SWTICHMS_REQ_t),

    XY_SUBSYS_TEXT_BASE = XY_SUBSYS_TEXT_REQ << 16,
    MSG_SHOW_NAME(XY_SUBSYS_TEXT_TXCFG_REQ,XY_SUBSYS_TEXT_TXCFG_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_TEXT_RXCFG_REQ,XY_SUBSYS_TEXT_RXCFG_REQ_t),
    MSG_SHOW_NAME(XY_SUBSYS_TEXT_START_REQ, nullStruct),
    MSG_SHOW_NAME(XY_SUBSYS_TEXT_STOP_REQ, nullStruct),


};

#endif
