#ifndef _XY_TYPE_DEFINE_
#define _XY_TYPE_DEFINE_

#ifndef MSG_SHOW_NAME
#define MSG_SHOW_NAME(id,struct_name)   id
#endif

#define DIAG_RSP_STRUCT_NONE 

typedef enum
{
	XY_SUBSYS_CAIL_REQ = 1,
	XY_SUBSYS_TEXT_REQ,
	XY_SUBSYS_CAIL_CNF,
	XY_SUBSYS_TEXT_CNF,
	XY_SYSAPP_REQ,
	XY_SYSAPP_CNF,
	XY_SYSSUB_REQ,
	XY_SYSSUB_CNF,
	XY_AT_CMD = 101,
	XY_FOTA_CMD,

	XY_BLE_AT_CMD = 150,
}XY_BLOCK_e;

typedef enum
{
	XY_STATIC_LOG = 0x01,
	XY_DYNAMIC_LOG,
	XY_AT_LOG,
	XY_MESSAGE_LOG,
	XY_PROTOCOL_LOG,
	XY_SYSAPPREQ_LOG,
	XY_SYSAPPCNF_LOG,
	XY_SUBSYSREQ_LOG,
	XY_SUBSYSCNF_LOG,
	XY_MEMORY_LOG,
	XM_MAX_LOT = 0xF
}XY_TRANSPORT_e;

typedef enum
{
	START_DUMP,
	REV_PCCMD,
}XY_DUMP_FLAG;

#define DIAG_TAIL_LEN 2
#endif
