#ifndef NBIOT_MSG_HEADER_
#define NBIOT_MSG_HEADER_
#include "softap_macro.h"
#if IS_DSP_CORE
#include "vos_type.h"
#endif

#ifndef MSG_SHOW_NAME
#define MSG_SHOW_NAME(id, name) id
#endif

typedef enum
{
	ADMIN_PS_AP_CLASS 	,
	LPHY_DLMAC_AP_CLASS ,
	LPHY_ULMAC_AP_CLASS ,
	LPHY_LRRC_AP_CLASS  ,
	DLMAC_LRRC_AP_CLASS ,
	ULMAC_LRRC_AP_CLASS ,
	ULRLC_LRRC_AP_CLASS ,
	ULRLC_LPDCP_AP_CLASS,
	DLRLC_LRRC_AP_CLASS ,
	DLRLC_LPDCP_AP_CLASS,
	LPDCP_LRRC_AP_CLASS ,
	LRRC_NAS_AP_CLASS   ,
	LPDCP_NAS_AP_CLASS  ,
	USIM_PS_AP_CLASS    ,
	OM_PS_AP_CLASS      ,
	ATC_NAS_AP_CLASS    ,
	APP_PS_AP_CLASS     ,
	ATC_SMS_AP_CLASS    ,
	PS_RRC_CLASS  ,     /* 3G/LTE/LNB RRC Message                       */
	PS_NAS_CLASS  ,     /* RR/MM/GMM/CC/SS/EPS Message  */  
}XY_NBLOT_MODULE_E;


#define MAX_MSG_ID 0x60 / 8

#define MAX_PS_BLOCK 20

typedef enum
{
		MSG_SHOW_NAME(WUEPS_START_REQ,			WUEPS_START_REQ_STRU ) 		= 	0x00000000,
		MSG_SHOW_NAME(PS_POWER_OFF_REQ, 		PS_POWER_OFF_REQ_STRU ) 	= 	0x00000001,
		MSG_SHOW_NAME(WUEPS_RESTART_REQ,		WUEPS_RESTART_REQ_STRU) 	=	0x00000002,
		MSG_SHOW_NAME(PS_POWER_OFF_CNF, 		PS_POWER_OFF_CNF_STRU )		=	0x00000003,
		MSG_SHOW_NAME(WUEPS_START_CNF,			WUEPS_START_CNF_STRU  )		=	0x00000004,
		MSG_SHOW_NAME(WUEPS_RESTART_CNF,		WUEPS_RESTART_CNF_STRU)		=	0x00000005,
		MSG_SHOW_NAME(WUEPS_ERROR_RPT_IND,		WUEPS_ERROR_RPT_IND_STRU)	=	0x00000006,
		MSG_SHOW_NAME(PS_COMM_READY_IND,		PS_COMM_READY_IND_STRU)		=	0x00000007,
		MSG_SHOW_NAME(PS_POWER_OFF_IND, 		PS_POWER_OFF_IND_STRU)		=	0x00000008,
		MSG_SHOW_NAME(D_ADMIN_PS_RESTART_CNF,	ST_ADMIN_PS_RESTART_CNF)	=	0x00000009,
		MSG_SHOW_NAME(WUEPS_ACTIVE_REQ, 		WUEPS_ACTIVE_REQ_STRU)		=	0x0000000a,
		MSG_SHOW_NAME(WUEPS_ACTIVE_CNF, 		WUEPS_ACTIVE_CNF_STRU)		=	0x0000000b,
		MSG_SHOW_NAME(WUEPS_DEACTIVE_IND,		WUEPS_DEACTIVE_IND_STRU)	=	0x0000000c,

}ADMIN_PS_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_PHY_DL_SCH_DATA_IND,         LNB_PhyDlSchData_Ind_Payload_STRU)        = 0x0000,
	MSG_SHOW_NAME(LNB_PHY_BCH_DATA_IND,            LNB_PhyBchData_Ind_Payload_STRU)          = 0x0001,
	MSG_SHOW_NAME(LNB_PHY_DL_SCH_DATA_IND_LEVEL1,  LNB_PhyDlSchData_Ind_Level1_STRU)         = 0x0002,
}LPHY_DLMAC_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_PHY_ACCESS_REQ,				LNB_PhyAccess_Req_STRU) 				= 0x0000,
	MSG_SHOW_NAME(LNB_PHY_ACCESS_RESP_IND,			LNB_PhyAccessResp_Ind_Payload_STRU)     = 0x0001,
	MSG_SHOW_NAME(LNB_PHY_ACCESS_STOP_REQ,			LNB_PhyAccessStop_Req_STRU)				= 0x0002,
	MSG_SHOW_NAME(LNB_PHY_PDCCH_ORDER_IND,			LNB_PhyPdcchOrder_Ind_STRU)				= 0x0003,
	MSG_SHOW_NAME(LNB_PHY_RAR_GRANT_CONFIG_REQ, 	LNB_PhyRARGrantConfig_Req_STRU)			= 0x0004,
	MSG_SHOW_NAME(LNB_PHY_FLUSH_HARQ_BUFFER_REQ,	LNB_PhyFlushHarqBuffer_Req_STRU)		= 0x0005,
	MSG_SHOW_NAME(LNB_PHY_CR_END_REQ,				LNB_PhyCREnd_Req_STRU)					= 0x0006,
	MSG_SHOW_NAME(LNB_PHY_CR_TIMER_OUT_IND,			LNB_PhyCRTimerOut_Ind_STRU)				= 0x0007,
	MSG_SHOW_NAME(LNB_PHY_CRNTI_CONFIG_REQ,			LNB_PhyCRNTIConfig_Req_STRU)			= 0x0008,
	MSG_SHOW_NAME(LNB_PHY_TA_CONFIG_REQ,			LNB_PhyTAConfig_Req_STRU)				= 0x0009,
	MSG_SHOW_NAME(LNB_PHY_DRX_COMMAND_REQ,			LNB_PhyDrxCommand_Req_STRU)				= 0x000a,
	MSG_SHOW_NAME(LNB_PHY_GET_RSRP_REQ,				LNB_PhyGetRSRP_Req_STRU)				= 0x000b,
	MSG_SHOW_NAME(LNB_PHY_GET_RSRP_IND,				LNB_PhyGetRSRP_Ind_STRU)				= 0x000c,
	MSG_SHOW_NAME(LNB_PHY_GET_UL_DATA_REQ,			LNB_PhyGetUlData_Req_STRU)				= 0x000d,
	MSG_SHOW_NAME(LNB_PHY_GET_UL_DATA_CNF,			LNB_PhyGetUlData_Cnf_Payload_STRU)		= 0x000e,
	MSG_SHOW_NAME(LNB_PHY_RAPID_CHECK_FAILED_REQ,	LNB_PhyRapidCheckFailedReq_STRU)		= 0x000f,
	MSG_SHOW_NAME(LNB_PHY_RA_RESET_REQ,	            LNB_PhyRaReset_Req_STRU)		        = 0x0010,
	MSG_SHOW_NAME(LNB_PHY_GET_UL_DATA_CNF_LEVEL1,	LNB_PhyGetUlData_Cnf_Level1_STRU)       = 0x0011,
	
}LPHY_ULMAC_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_CPHY_FREQ_SCAN_REQ,					LNB_PHY_FREQ_SCAN_REQ_STRU	) 	= 0x0000,
	MSG_SHOW_NAME(LNB_CPHY_FREQ_SCAN_CNF,					LNB_PHY_FREQ_SCAN_CNF_STRU	) 	= 0x0001,
	MSG_SHOW_NAME(LNB_CPHY_CELL_DETECT_REQ, 				LNB_PHY_CELL_DETECT_REQ_STRU) 	= 0x0002,
	MSG_SHOW_NAME(LNB_CPHY_CELL_DETECT_CNF, 				LNB_PHY_CELL_DETECT_CNF_STRU) 	= 0x0003,
	MSG_SHOW_NAME(LNB_CPHY_GET_MIB_REQ, 					LNB_PHY_GET_MIB_REQ_STRU	) 	= 0x0004,
	MSG_SHOW_NAME(LNB_CPHY_GET_SIB1_REQ,					LNB_PHY_GET_SIB1_REQ_STRU)	 	= 0x0005,
	MSG_SHOW_NAME(LNB_CPHY_GET_SI_REQ,						LNB_PHY_GET_SI_REQ_STRU) 		= 0x0006,
	MSG_SHOW_NAME(LNB_CPHY_STOP_GET_SI_REQ, 				LNB_PHY_STOP_GET_SIB_REQ_STRU) 	= 0x0007,
	MSG_SHOW_NAME(LNB_CPHY_OUT_OF_SYNC_IND, 				LNB_PHY_OUT_OF_SYNC_IND_STRU) 	= 0x0008,
	MSG_SHOW_NAME(LNB_CPHY_IN_SYNC_IND, 					LNB_PHY_IN_SYNC_IND_STRU) 		= 0x0009,
	MSG_SHOW_NAME(LNB_CPHY_INTRA_FREQ_CELL_MEAS_CFG_REQ,	LNB_PHY_INTRAF_CELL_MEAS_CFG_REQ_STRU) = 0x000a,
	MSG_SHOW_NAME(LNB_CPHY_INTRA_FREQ_CELL_MEAS_IND,		LNB_PHY_INTRA_FREQ_CELL_MEAS_IND_STRU) = 0x000b,
	MSG_SHOW_NAME(LNB_CPHY_INTER_FREQ_CELL_MEAS_CFG_REQ,	LNB_PHY_INTERF_CELL_MEAS_CFG_REQ_STRU) = 0x000c,
	MSG_SHOW_NAME(LNB_CPHY_INTER_FREQ_CELL_MEAS_IND,		LNB_PHY_INTER_FREQ_CELL_MEAS_IND_STRU) = 0x000d,
	MSG_SHOW_NAME(LNB_CPHY_COMMON_CH_CONFIG_REQ,			LNB_PHY_COMMON_CH_CONFIG_PAYLOAD_STRU) = 0x000e,
	MSG_SHOW_NAME(LNB_CPHY_COMMON_CH_CONFIG_CNF,			LNB_PHY_COMMON_CH_CONFIG_CNF_STRU)	= 0x000f,
	MSG_SHOW_NAME(LNB_CPHY_DEDICATE_CH_CONFIG_REQ,			LNB_PHY_DEDICATE_CH_CONFIG_REQ_STRU) 	= 0x0010,
	MSG_SHOW_NAME(LNB_CPHY_DEDICATE_CH_CONFIG_CNF,			LNB_PHY_DEDICATE_CH_CONFIG_CNF_STRU) 	= 0x0011,
	MSG_SHOW_NAME(LNB_CPHY_RESET_REQ,						LNB_PHY_RESET_REQ_STRU) 				= 0x0012,
	MSG_SHOW_NAME(LNB_CPHY_RESET_CNF,						LNB_PHY_RESET_CNF_STRU	) 				= 0x0013,
	MSG_SHOW_NAME(LNB_CPHY_EDRX_SLEEP_IND,					LNB_PHY_EDRX_SLEEP_IND_STRU) 			= 0x0014,
	MSG_SHOW_NAME(LNB_CPHY_LOST_CELL_IND,					LNB_PHY_LOST_CELL_IND_STRU)  			= 0x0015,
	MSG_SHOW_NAME(LNB_CPHY_N310_OUT_OF_SYNC_IND,			LNB_PHY_N310_OUT_OF_SYNC_IND_STRU) 		= 0x0016,
	MSG_SHOW_NAME(LNB_CPHY_N311_IN_SYNC_IND,				LNB_PHY_N311_IN_SYNC_IND_STRU) 			= 0x0017,
	MSG_SHOW_NAME(LNB_CPHY_CH_RELEASE_REQ,					LNB_PHY_CHANNEL_RELEASE_REQ_STRU) 			= 0x0018,
	MSG_SHOW_NAME(LNB_CPHY_CH_RELEASE_CNF,					LNB_PHY_CHANNEL_RELEASE_CNF_STRU) 			= 0x0019,
	MSG_SHOW_NAME(LNB_CPHY_CQI_IND,							LNB_PHY_CQI_IND_STRU) 			= 0x001A,
	MSG_SHOW_NAME(LNB_CPHY_PRS_MEAS_CFG_REQ,				LCPHY_PRS_MEAS_CFG_REQ_Payload_STRU)    = 0x001B,
	MSG_SHOW_NAME(LNB_CPHY_PRS_MEAS_RPT_REQ,				LCPHY_PRS_MEAS_RPT_REQ_STRU) 			= 0x001C,
	MSG_SHOW_NAME(LNB_CPHY_PRS_MEAS_RLT_IND,				LCPHY_PRS_MEAS_RLT_IND_Payload_STRU) 	= 0x001D,
	MSG_SHOW_NAME(LNB_CPHY_PRS_MEAS_DEL_REQ,				LCPHY_PRS_MEAS_DEL_REQ_STRU) 			= 0x001E,

}LPHY_LRRC_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_DLMAC_CCCH_DATA_IND,					LNB_DL_MAC_CCCH_DATA_IND_STRU) = 0x0001,
	MSG_SHOW_NAME(LNB_DLMAC_DL_CRNTI_DATA_IND,				LNB_DL_MAC_DL_CRNTI_DATA_IND_STRU)= 0x0002,
	MSG_SHOW_NAME(LNB_DLMAC_TA_IND, 						LNB_DL_MAC_TA_IND_STRU)= 0x0003,

}DLMAC_ULMAC_AP_CLASS_E;

typedef enum
{
	DLMAC_DLRLC_AP_CLASS_NODEFINE,
}DLMAC_DLRLC_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_MAC_RRC_DATA_IND,						LNB_MAC_RRC_DATA_IND_STRU) = 0x000A,
	MSG_SHOW_NAME(LNB_MAC_DATA_INACTIVITY_TIMEROUT_IND, 	LNB_MAC_DATA_INACTIVITY_TIMEROUT_IND_STRU) = 0x000B,
	MSG_SHOW_NAME(LNB_MAC_UPDATE_ACCESS_REQ, 				LNB_MAC_UPDATE_ACCESS_REQ_STRU) = 0x000C,
	                
}DLMAC_LRRC_AP_CLASS_E;

typedef enum
{
	ULMAC_ULRLC_AP_CLASS_NODEFINE,
}ULMAC_ULRLC_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_MAC_CFG_REQ,							LNB_MAC_CFG_REQ_STRU) = 0x0000,
	MSG_SHOW_NAME(LNB_MAC_CFG_CNF,							LNB_MAC_CFG_CNF_STRU) = 0x0001,
	MSG_SHOW_NAME(LNB_MAC_ACCESS_REQ,						LNB_MAC_ACCESS_REQ_STRU) = 0x0002,
	MSG_SHOW_NAME(LNB_MAC_ACCESS_CNF,						LNB_MAC_ACCESS_CNF_STRU) = 0x0003,
	MSG_SHOW_NAME(LNB_MAC_ACCESS_FAILURE_IND,				LNB_MAC_ACCESS_FAILURE_IND_STRU) = 0x0004,
	MSG_SHOW_NAME(LNB_MAC_RST_REQ,							LNB_MAC_RST_REQ_STRU) = 0x0005,
	MSG_SHOW_NAME(LNB_MAC_RST_CNF,							LNB_MAC_RST_CNF_STRU) = 0x0006,
	MSG_SHOW_NAME(LNB_MAC_RLS_REQ,							LNB_MAC_RLS_REQ_STRU) = 0x0007,
	MSG_SHOW_NAME(LNB_MAC_RLS_CNF,							LNB_MAC_RLS_CNF_STRU) = 0x0008,
	MSG_SHOW_NAME(LNB_MAC_CCCH_DATA_IND,					LNB_MAC_CCCH_DATA_IND_STRU) = 0x0009,
	MSG_SHOW_NAME(LNB_MAC_RSRP_IND,					        LNB_MAC_RSRP_IND_STRU) = 0x000D,
}ULMAC_LRRC_AP_CLASS_E;

typedef enum
{
	DLRLC_ULRLC_AP_CLASS_NODEFINE,
}DLRLC_ULRLC_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_RLC_CFG_REQ,							LNB_RLC_CFG_REQ_STRU) 		= 0x0000,
	MSG_SHOW_NAME(LNB_RLC_CFG_CNF,							LNB_RLC_CFG_CNF_STRU) 		= 0x0001,
	MSG_SHOW_NAME(LNB_RLC_REEST_REQ,						LNB_RLC_REEST_REQ_STRU) 	= 0x0002,
	MSG_SHOW_NAME(LNB_RLC_REEST_CNF,						LNB_RLC_REEST_CNF_STRU) 	= 0x0003,
	MSG_SHOW_NAME(LNB_RLC_RLS_REQ,							LNB_RLC_RLS_REQ_STRU) 		= 0x0004,
	MSG_SHOW_NAME(LNB_RLC_RLS_CNF,							LNB_RLC_RLS_CNF_STRU) 		= 0x0005,
	MSG_SHOW_NAME(LNB_RLC_SUSPEND_REQ,						LNB_RLC_SUSPEND_REQ_STRU) 	= 0x0006,
	MSG_SHOW_NAME(LNB_RLC_SUSPEND_CNF,						LNB_RLC_SUSPEND_CNF_STRU) 	= 0x0007,
	MSG_SHOW_NAME(LNB_RLC_RESUME_REQ,						LNB_RLC_RESUME_REQ_STRU) 	= 0x0008,
	MSG_SHOW_NAME(LNB_RLC_RESUME_CNF,						LNB_RLC_RESUME_CNF_STRU) 	= 0x0009,
	MSG_SHOW_NAME(LNB_RLC_LINKLOSS_IND, 					LNB_RLC_LINKLOSS_IND_STRU) 	= 0x000A,
	MSG_SHOW_NAME(LNB_RLC_RELEASE_ACK_REQ,					LNB_RLC_RELEASE_ACK_REQ_STRU) 		= 0x000B,
	MSG_SHOW_NAME(LNB_RLC_ACK_SND_IND,						LNB_RLC_ACK_SND_IND_STRU) 			= 0x000C,
	MSG_SHOW_NAME(MSG_LNB_RLC_AM_DATA_REQ,						LNB_RLC_AM_DATA_REQ_Payload_STRU) = 0x00000013,
	MSG_SHOW_NAME(MSG_LNB_RLC_AM_DATA_CNF,						LNB_RLC_AM_DATA_CNF_STRU) = 0x00000015,
	

}ULRLC_LRRC_AP_CLASS_E;
 

typedef enum
{	
	MSG_SHOW_NAME(MSG_LNB_RLC_AM_DATA_REQ_,						LNB_RLC_AM_DATA_REQ_Payload_STRU) = 0x00000013,
	MSG_SHOW_NAME(MSG_LNB_RLC_PDU_DISCARD_REQ,					LNB_RLC_PDU_DISCARD_REQ_Payload_STRU) = 0x0014,
	MSG_SHOW_NAME(MSG_LNB_RLC_AM_DATA_CNF_,						LNB_RLC_AM_DATA_CNF_STRU) = 0x00000015,

}ULRLC_LPDCP_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(MSG_LNB_RLC_AM_DATA_IND,					LNB_RLC_AM_DATA_IND_Payload_STRU) = 0x0016,

}DLRLC_LRRC_AP_CLASS_E;

typedef enum
{	
	MSG_SHOW_NAME(MSG_LNB_RLC_AM_DATA_IND_,					LNB_RLC_AM_DATA_IND_Payload_STRU) = 0x0016,
}DLRLC_LPDCP_AP_CLASS_E;

typedef enum
{	
	MSG_SHOW_NAME(MSG_LNB_PDCP_CONFIG_REQ,					LNB_PDCP_CONFIG_REQ_STRU) = 0,
	MSG_SHOW_NAME(MSG_LNB_PDCP_REEST_REQ,					LNB_PDCP_REEST_REQ_STRU) = 1,
	MSG_SHOW_NAME(MSG_LNB_PDCP_REEST_COMP_REQ,				LNB_PDCP_REEST_COMP_REQ_STRU) = 2,
	MSG_SHOW_NAME(MSG_LNB_PDCP_RELEASE_REQ,					LNB_PDCP_RELEASE_REQ_STRU) = 3,
	MSG_SHOW_NAME(MSG_LNB_PDCP_CONFIG_CNF,					LNB_PDCP_CONFIG_CNF_STRU) = 4,
	MSG_SHOW_NAME(MSG_LNB_PDCP_REEST_CNF,					LNB_PDCP_REEST_CNF_STRU) = 5,
	MSG_SHOW_NAME(MSG_LNB_PDCP_RELEASE_CNF,					LNB_PDCP_RELEASE_CNF_STRU) = 6,
	MSG_SHOW_NAME(MSG_LNB_PDCP_SUSPEND_REQ,					LNB_PDCP_SUSPEND_REQ_STRU) = 7,
	MSG_SHOW_NAME(MSG_LNB_PDCP_RESUME_REQ,					LNB_PDCP_RESUME_REQ_STRU) = 8,
	MSG_SHOW_NAME(MSG_LNB_PDCP_SUSPEND_CNF,					LNB_PDCP_SUSPEND_CNF_STRU) = 9,
	MSG_SHOW_NAME(MSG_LNB_PDCP_RESUME_CNF,					LNB_PDCP_RESUME_CNF_STRU) = 10,
	MSG_SHOW_NAME(MSG_LNB_PDCP_PSM_REQ,						LNB_PDCP_PSM_REQ_STRU) = 11,
	MSG_SHOW_NAME(MSG_LNB_PDCP_PSM_RESP,					LNB_PDCP_PSM_RESP_Payload_STRU) = 12,
	MSG_SHOW_NAME(MSG_LNB_PDCP_PSM_CNF,					    LNB_PDCP_PSM_CNF_Payload_STRU) = 13,
}LPDCP_LRRC_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_RRC_EST_REQ,							LNB_RRC_EST_REQ_TEST_LONG_INFO_STRU) = 0x00000000,
	MSG_SHOW_NAME(LNB_RRC_DATA_REQ,							LNB_RRC_DATA_REQ_TEST_LONG_INFO_STRU) = 0x00000001,
	MSG_SHOW_NAME(LNB_RRC_CONN_REL_REQ,						LNB_RRC_CONN_REL_REQ_STRU) = 0x00000002,
	MSG_SHOW_NAME(LNB_RRC_INFO_CHANGE_IND,					LNB_RRC_INFO_CHANGE_IND_TEST_LONG_INFO_STRU) = 0x00000003,
	MSG_SHOW_NAME(LNB_RRC_EST_CNF,							LNB_RRC_EST_CNF_STRU) = 0x00000004,
	MSG_SHOW_NAME(LNB_RRC_DATA_CNF,							LNB_RRC_DATA_CNF_STRU) = 0x00000005,
	MSG_SHOW_NAME(LNB_RRC_DATA_IND,							LNB_RRC_Test_DATA_IND_STRU) = 0x00000006,
	MSG_SHOW_NAME(LNB_RRC_SYS_INFO_IND,						LNB_RRC_SYS_INFO_IND_STRU ) = 0x00000007,
	MSG_SHOW_NAME(LNB_RRC_PAGING_IND,						LNB_RRC_PAGING_IND_STRU) = 0x00000008,
	MSG_SHOW_NAME(LNB_RRC_CONN_REL_IND,						LNB_RRC_CONN_REL_IND_STRU) = 0x00000009,
	MSG_SHOW_NAME(LNB_RRC_RADIO_QUAL_IND,					LNB_RRC_RADIO_QUAL_IND_STRU) = 0x0000000A,
	MSG_SHOW_NAME(LNB_RRC_DRB_CHG_IND,						LNB_RRC_DRB_CHG_IND_STRU) = 0x0000000B,
	MSG_SHOW_NAME(LNB_RRC_START_REQ,						LNB_RRC_START_REQ_STRU) = 0x0000000C,
	MSG_SHOW_NAME(LNB_RRC_START_CNF,						LNB_RRC_START_CNF_STRU) = 0x0000000D,
	MSG_SHOW_NAME(LNB_RRC_PLMN_SEARCH_REQ,					LNB_RRC_PLMN_SEARCH_REQ_TEST_LONG_INFO_STRU) = 0x0000000E,
	MSG_SHOW_NAME(LNB_RRC_PLMN_SEARCH_CNF,					LNB_RRC_PLMN_SEARCH_CNF_STRU) = 0x0000000F,
	MSG_SHOW_NAME(LNB_RRC_POWER_OFF_REQ,					LNB_RRC_POWER_OFF_REQ_STRU) = 0x00000010,
	MSG_SHOW_NAME(LNB_RRC_POWER_OFF_CNF,					LNB_RRC_POWER_OFF_CNF_STRU) = 0x00000011,
	MSG_SHOW_NAME(LNB_RRC_OOS_IND,							LNB_RRC_OOS_IND_STRU)= 0x00000012,
	MSG_SHOW_NAME(LNB_RRC_RESUME_FALLBACK_IND,				LNB_RRC_RESUME_FALLBACK_IND_STRU) = 0x00000013,
	MSG_SHOW_NAME(LNB_RRC_DEACTIVE_REQ,						LNB_RRC_DEACTIVE_REQ_STRU) = 0x00000014,
	MSG_SHOW_NAME(LNB_RRC_SMC_INFO_IND,						LNB_RRC_SMC_INFO_IND_STRU) = 0x00000015,
	MSG_SHOW_NAME(LNB_RRC_DEACTIVE_CNF,						MSG_HEADER_STRU) = 0x00000016,
	MSG_SHOW_NAME(LNB_RRC_ACTIVE_REQ  ,						LNB_RRC_ACTIVE_REQ_STRU) = 0x00000017,
	MSG_SHOW_NAME(LNB_RRC_ACTIVE_CNF  ,						LNB_RRC_ACTIVE_CNF_STRU) = 0x00000018,
	MSG_SHOW_NAME(LNB_RRC_EDRX_SLEEP_IND,					LNB_RRC_EDRX_SLEEP_IND_STRU) = 0x00000019,
	MSG_SHOW_NAME(LNB_RRC_AT_NEARFCN_REQ,					LNB_RRC_AT_NEARFCN_REQ_STRU) = 0x0000001A,
	MSG_SHOW_NAME(LNB_RRC_DATA_IND_LONG_INFO,				MSG_HEADER_STRU)			 = 0x0000001C,
	MSG_SHOW_NAME(LNB_LPP_LOCA_MEAS_CFG_REQ,				LPP_LOCA_MEAS_CFG_REQ_STRU)  = 0x0000001D,
	MSG_SHOW_NAME(LNB_LPP_LOCA_MEAS_DEL_REQ,				LPP_LOCA_MEAS_DEL_REQ_STRU)	 = 0x0000001E,
	MSG_SHOW_NAME(LNB_LPP_ASSIST_DATA_REQ,				    LPP_ASSIST_DATA_REQ_STRU) = 0x0000001F,
	MSG_SHOW_NAME(LNB_LPP_ASSIST_DATA_DEL_REQ,				LPP_LOCA_ASSTDATA_DEL_REQ_STRU) = 0x00000020,
}LRRC_NAS_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(MSG_LNB_PDCP_DATA_REQ,					LNB_PDCP_DATA_REQ_Payload_STRU) = 0,
	MSG_SHOW_NAME(MSG_LNB_PDCP_DATA_IND,					LNB_PDCP_DATA_IND_Payload_STRU),
	MSG_SHOW_NAME(MSG_LNB_PDCP_UL_FC_IND,					LNB_PDCP_UL_FC_IND_STRU),

}LPDCP_NAS_AP_CLASS_E;


typedef enum
{
	MSG_SHOW_NAME(UICC_STATUS_REQ,							UICC_STATUS_REQ_MSG_STRU) = 0x00000000,
	MSG_SHOW_NAME(UICC_STATUS_CNF,							UICC_STATUS_CNF_MSG_STRU) = 0x00000001,
	MSG_SHOW_NAME(UICC_READ_FILE_REQ,						UICC_READ_FILE_REQ_MSG_STRU) =  0x00000002 ,
	MSG_SHOW_NAME(UICC_STATUS_IND,							UICC_STATUS_IND_MSG_STRU) =  0x00000003,
	MSG_SHOW_NAME(UICC_UPDATE_FILE_REQ, 					UICC_UPDATE_FILE_REQ_MSG_LOG_STRU)= 0x00000004,
	MSG_SHOW_NAME(UICC_READ_FILE_CNF,						UICC_READ_FILE_CNF_MSG_LOG_STRU)=  0x00000005,
	MSG_SHOW_NAME(UICC_USIM_AUTHENTICATION_REQ, 			UICC_USIM_AUTH_REQ_MSG_STRU)= 0x00000006,
	MSG_SHOW_NAME(UICC_USIM_AUTHENTICATION_CNF, 			UICC_USIM_AUTHENTICATION_CNF_MSG_STRU)= 0x00000007,
	MSG_SHOW_NAME(UICC_RESTRICTED_ACCESS_REQ,				UICC_RESTRICT_ACCESS_REQ_MSG_STRU)= 0x00000008,
	MSG_SHOW_NAME(UICC_MM_RESTART_IND,						UICC_MM_RESTART_IND_STRU)= 0x00000009,
	MSG_SHOW_NAME(UICC_PIN_CHECK_REQ,						UICC_PIN_CHECK_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_USER_PLMN_CHANGE_IND,				UICC_USER_PLMN_CHANGE_IND_STRU),
	MSG_SHOW_NAME(UICC_PIN_STATUS_READ_REQ, 				UICC_PIN_STATUS_READ_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_UPDATE_FILE_CNF, 					UICC_UPDATE_FILE_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_PIN_CHANGE_REQ,						UICC_PIN_CHANGE_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_RESTRICTED_ACCESS_CNF,				UICC_RESTRICT_ACC_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_USAT_REFRESH_RSP,					UICC_USAT_REFRESH_RSP_MSG_STRU),
	MSG_SHOW_NAME(UICC_PIN_STATUS_READ_CNF, 				UICC_PIN_STATUS_READ_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_PIN_CHANGE_CNF,						UICC_PIN_CHANGE_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_LOCK_REQ,							UICC_LOCK_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_LOCK_CNF,							UICC_LOCK_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_USAT_REFRESH_IND,					UICC_USAT_REFRESH_IND_MSG_STRU),
	MSG_SHOW_NAME(UICC_GSM_AUTHENTICATION_REQ,				MSG_HEADER_STRU),
	MSG_SHOW_NAME(UICC_GSM_AUTHENTICATION_CNF,				MSG_HEADER_STRU),	
	MSG_SHOW_NAME(UICC_PIN_CHECK_CNF,						UICC_PIN_CHECK_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_GET_RECORD_FILE_STATUS_REQ,			UICC_GET_RECORD_FILE_STATUS_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_READ_RECORD_CNF, 					UICC_READ_RECORD_CNF_MSG_LOG_STRU),
	MSG_SHOW_NAME(UICC_READ_RECORD_REQ, 					UICC_READ_RECORD_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_UPDATE_RECORD_REQ,					UICC_UPDATE_RECORD_REQ_MSG_LOG_STRU),
	MSG_SHOW_NAME(UICC_UPDATE_RECORD_CNF,					UICC_UPDATE_RECORD_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_GET_RECORD_FILE_STATUS_CNF,			UICC_GET_RECORD_FILE_STATUS_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_PIN_VER_IND, 						UICC_PIN_VER_IND_STRU),
	MSG_SHOW_NAME(UICC_PUK_VER_IND, 						UICC_PUK_VER_IND_STRU),
	MSG_SHOW_NAME(UICC_PUK_BLOCKED_IND, 					UICC_PUK_BLOCKED_IND_STRU),
	MSG_SHOW_NAME(UICC_CHANGE_FILE_STATUS_REQ,				MSG_HEADER_STRU),
	MSG_SHOW_NAME(UICC_CHANGE_FILE_STATUS_CNF,				UICC_CHANGE_FILE_STATUS_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_SUSPEND_REQ, 						UICC_SUSPEND_REQ_MSG_STRU) = 0x0000002E,
	MSG_SHOW_NAME(UICC_SUSPEND_CNF, 						UICC_SUSPEND_CNF_MSG_STRU)= 0x0000002F,
	MSG_SHOW_NAME(UICC_RESUME_REQ,							UICC_RESUME_REQ_MSG_STRU)= 0x00000030,
	MSG_SHOW_NAME(UICC_RESUME_CNF,							UICC_RESUME_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_PERIOD_DETECT_CTRL_IND,				UICC_PERIOD_DETECT_CTRL_IND_MSG_STRU),
	MSG_SHOW_NAME(UICC_PRESENT_DETECT_REQ,					UICC_PRESENT_DETECT_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_PRESENT_DETECT_CNF,					UICC_PRESENT_DETECT_CNF_MSG_STRU),
#ifdef BIP_FEATURE
	MSG_SHOW_NAME(UICC_SMS_DATA_REQ,				        UICC_SMS_DATA_REQ_STRU),
	MSG_SHOW_NAME(UICC_SMS_DATA_CNF,					    UICC_SMS_DATA_CNF_STRU),
	MSG_SHOW_NAME(UICC_SMS_DATA_IND,					    UICC_SMS_DATA_IND_STRU),
	MSG_SHOW_NAME(UICC_SMS_DATA_RSP,					    UICC_SMS_DATA_RSP_STRU),
	MSG_SHOW_NAME(UICC_BIP_CREATE_SOCKET_CNF,				BIP_CREATE_SOCKET_CNF),
	MSG_SHOW_NAME(UICC_BIP_SEND_DATA_CNF,					BIP_SEND_DATA_CNF),
	MSG_SHOW_NAME(UICC_BIP_RECIVE_DATA_IND,					BIP_DATA_IND),
	MSG_SHOW_NAME(UICC_BIP_SOCKET_CLOSE_IND,				BIP_CLOSE_SOCKET_IND),
	MSG_SHOW_NAME(UICC_EVENT_DATA_AVAILABLE,				EVET_DATA_AVALIABLE_IND),
	MSG_SHOW_NAME(UICC_EVENT_CHANL_STATUS,					EVET_CHANL_STATIS_IND),
	MSG_SHOW_NAME(UICC_RESET_IND,					        BIP_SEND_RESET_IND),
	MSG_SHOW_NAME(UICC_BIP_CLOSE_SOCKET_CNF,				BIP_CLOSE_SOCKET_CNF),
	MSG_SHOW_NAME(BIP_MSG_CREATE_SOCKET_REQ,				BIP_CREATE_SOCKET_REQ),
	MSG_SHOW_NAME(BIP_MSG_CLOSE_SOCKET_REQ,					BIP_CREATE_SOCKET_REQ),
	MSG_SHOW_NAME(BIP_MSG_SEND_DATA_REQ,				    BIP_SEND_DATA_REQ),
#endif	
    MSG_SHOW_NAME(UICC_PIN_RETRIES_REQ,                     UICC_PIN_RETRIES_REQ_MSG_STRU)= 0x00000044,
    MSG_SHOW_NAME(UICC_PIN_RETRIES_CNF,                     UICC_PIN_RETRIES_CNF_MSG_STRU),
    
	MSG_SHOW_NAME(UICC_DRIVE_CARD_INSERT,					MSG_HEADER_STRU) = 0x00000024,
	MSG_SHOW_NAME(UICC_DRIVE_CARD_REMOVE,					MSG_HEADER_STRU),
	MSG_SHOW_NAME(UICC_DEACTIVE_UICC_REQ,					MSG_HEADER_STRU),
	MSG_SHOW_NAME(UICC_TERMINAL_PROFILE_REQ,				MSG_HEADER_STRU),
	MSG_SHOW_NAME(UICC_ENVELOP_REQ, 						MSG_HEADER_STRU),	
	MSG_SHOW_NAME(UICC_TERMINAL_RSP_REQ,					MSG_HEADER_STRU),
	MSG_SHOW_NAME(UICC_MANAGE_CHANNEL_REQ,					UICC_MANAGE_CHANNEL_REQ_MSG_STRU)= 0x0000002A,
	MSG_SHOW_NAME(UICC_MANAGE_CHANNEL_CNF,					UICC_MANAGE_CHANNEL_CNF_MSG_STRU),
	MSG_SHOW_NAME(UICC_USIM_ACCESS_REQ, 					UICC_USIM_ACCESS_REQ_MSG_STRU),
	MSG_SHOW_NAME(UICC_USIM_ACCESS_CNF, 					UICC_USIM_ACCESS_CNF_MSG_STRU),

}USIM_PS_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(LNB_DLMAC_GLOBAL_GET_REQ, 				MSG_HEADER_STRU) = 0x00000000, 
	MSG_SHOW_NAME(LNB_DLMAC_GLOBAL_GET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_DLMAC_GLOBAL_SET_REQ, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_DLMAC_GLOBAL_SET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULMAC_GLOBAL_GET_REQ, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULMAC_GLOBAL_GET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULMAC_GLOBAL_SET_REQ, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULMAC_GLOBAL_SET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_DLRLC_GLOBAL_GET_REQ, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_DLRLC_GLOBAL_GET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_DLRLC_GLOBAL_SET_REQ, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_DLRLC_GLOBAL_SET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULRLC_GLOBAL_GET_REQ, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULRLC_GLOBAL_GET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULRLC_GLOBAL_SET_REQ, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ULRLC_GLOBAL_SET_CNF, 				MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_RRCF_GLOBAL_GET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_RRCF_GLOBAL_GET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_RRCF_GLOBAL_SET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_RRCF_GLOBAL_SET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_PDCP_GLOBAL_GET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_PDCP_GLOBAL_GET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_PDCP_GLOBAL_SET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_PDCP_GLOBAL_SET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_NAS_GLOBAL_GET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_NAS_GLOBAL_GET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_NAS_GLOBAL_SET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_NAS_GLOBAL_SET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_SMS_GLOBAL_GET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_SMS_GLOBAL_GET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_SMS_GLOBAL_SET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_SMS_GLOBAL_SET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_EMM_GLOBAL_GET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_EMM_GLOBAL_GET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_EMM_GLOBAL_SET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_EMM_GLOBAL_SET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ESM_GLOBAL_GET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ESM_GLOBAL_GET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ESM_GLOBAL_SET_REQ,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_ESM_GLOBAL_SET_CNF,					MSG_HEADER_STRU), 
	MSG_SHOW_NAME(LNB_TIMEOUT_CHEATING_IND, 				LNB_TIMEOUT_CHEATING_IND_STRUCT) = 0x00000050,
	MSG_SHOW_NAME(LNB_POWERON_MODE_NOTIFY_IND,				LNB_POWERON_MODE_NOTIFY_IND_STRUCT) = 0x00000051,

}OM_PS_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(D_EPS_PDN_CONNECT_REQ,					LNB_PDN_CONNECT_REQ_STRU) 		= 0X00,
	MSG_SHOW_NAME(D_EPS_PDN_DISCONNECT_REQ,					LNB_PDN_DISCONNECT_REQ_STRU) 	= 0X01,
	MSG_SHOW_NAME(D_EPS_ATTACH_REQ,							LNB_ATTACH_REQ_STRU) 			= 0X02,
	MSG_SHOW_NAME(D_EPS_DETACH_REQ,							LNB_DETACH_REQ_STRU) 			= 0X03,
	MSG_SHOW_NAME(D_EPS_OPELIST_SRCH_REQ,					LNB_OPELIST_SRCH_REQ_STRU) 		= 0X04,
	MSG_SHOW_NAME(D_EPS_OPELIST_SRCH_ABORT_REQ,				MSG_HEADER_STRU) 				= 0X05,
	MSG_SHOW_NAME(D_EPS_OPERATOR_SELETE_REQ,				LNB_OPERATOR_SELETE_REQ_STRU) 	= 0X06,
	MSG_SHOW_NAME(D_EPS_OPESELINF_READ_REQ,					LNB_OPESELINF_READ_REQ_STRU) 	= 0X07,
	MSG_SHOW_NAME(D_EPS_BEARER_RESOURCE_ALLOC_REQ,			LNB_BEARER_RESOURCE_ALLOC_REQ_STRU)	 	= 0X08,
	MSG_SHOW_NAME(D_EPS_BEARER_RESOURCE_MODIFY_REQ,			LNB_BEARER_RESOURCE_MODIFY_REQ_STRU) 	= 0X09,
	MSG_SHOW_NAME(D_EPS_BEARER_CONTEXT_ACTIVE_RSP,			MSG_HEADER_STRU) 					 	= 0X0A,
	MSG_SHOW_NAME(D_EPS_OPERATOR_SELETE_ABORT_REQ,			MSG_HEADER_STRU) 						= 0X0B,
	MSG_SHOW_NAME(D_EPS_CSODCP_SEND_REQ,					LNB_EPS_CSODCP_SEND_REQ_STRU) 			= 0X0C,
	MSG_SHOW_NAME(D_EPS_CEDRXS_CPSMS_SET_REQ,				LNB_EPS_CPSMS_CEDRXS_SET_REQ_STRU) 		= 0X0D,
	MSG_SHOW_NAME(D_EPS_DEACTIVE_RESPONSE,					LNB_EPS_DEACTIVE_RESPONSE_STRU) 		= 0X0E,
	MSG_SHOW_NAME(D_EPS_ACTIVE_RESPONSE,					LNB_EPS_ACTIVE_RESPONSE_STRU) 			= 0X0F, 
		                                                                          
	MSG_SHOW_NAME(D_EPS_BEARER_ACTIVE_IND,					LNB_BEARER_ACTIVE_IND_STRU) = 0X10,
	MSG_SHOW_NAME(D_EPS_BEARER_MODIFY_IND,					LNB_BEARER_MODIFY_IND_STRU) = 0x11,
	MSG_SHOW_NAME(D_EPS_BEARER_DEACTIVE_IND,				LNB_BEARER_DEACTIVE_IND_STRU) = 0x12,
	MSG_SHOW_NAME(D_EPS_PDN_CONNECT_CNF,					LNB_PDN_CONNECT_CNF_STRU)= 0x13,
	MSG_SHOW_NAME(D_EPS_PDN_DISCONNECT_CNF,					LNB_PDN_DISCONNECT_CNF_STRU)= 0x14,
	MSG_SHOW_NAME(D_EPS_BEARER_RESOURCE_MODIFY_CNF,			LNB_BEARER_RESOURCE_MODIFY_CNF_STRU)= 0x15,
	MSG_SHOW_NAME(D_EPS_BEARER_RESOURCE_ALLOC_CNF,			LNB_BEARER_RESOURCE_ALLOC_CNF_STRU)= 0x16,
	MSG_SHOW_NAME(D_EPS_ATTACH_CNF,							LNB_ATTACH_CNF_STRU)= 0x17,
	MSG_SHOW_NAME(D_EPS_ATTACH_IND,							LNB_ATTACH_IND_STRU)= 0x18,
	MSG_SHOW_NAME(D_EPS_DETACH_CNF,							LNB_DETACH_CNF_STRU)= 0x19,
	MSG_SHOW_NAME(D_EPS_DETACH_IND,							LNB_DETACH_IND_STRU)= 0x1a,
	MSG_SHOW_NAME(D_EPS_RADIO_CELL_QUAL_INFO,				LNB_RADIO_QUAL_IND_STRU)= 0x1b,
	MSG_SHOW_NAME(D_EPS_OPELIST_SRCH_CNF,					LNB_OPELIST_SRCH_CNF_STRU)= 0x1c,
	MSG_SHOW_NAME(D_EPS_OPERATOR_SELETE_CNF,				LNB_OPERATOR_SELETE_CNF_STRU)= 0x1e,
	MSG_SHOW_NAME(D_EPS_USIM_STATUS_IND,					MSG_HEADER_STRU)= 0x20,	
	MSG_SHOW_NAME(D_EPS_EMM_INFO_IND,						LNB_EMM_INFO_IND_STRU)= 0x21,
	MSG_SHOW_NAME(D_EPS_START_COMP_IND,						LNB_START_COMP_IND_STRU)= 0x22,
	MSG_SHOW_NAME(D_EPS_PDN_CONNECT_IND,					LNB_PDN_CONNECT_IND_STRU)= 0x24,
	MSG_SHOW_NAME(D_EPS_DEACTIVE_IND,						LNB_EPS_DEACTIVE_IND_STRU)= 0x25,
	MSG_SHOW_NAME(D_EPS_CSODCP_CNF,							LNB_CSODCP_SEND_CNF_STRU)= 0x26,
	MSG_SHOW_NAME(D_EPS_CRTDCP_REPORT_IND,					LNB_CRTDCP_REPORT_IND_STRU)= 0x27,
	MSG_SHOW_NAME(D_EPS_CGAPNRC_INFO_IND,					LNB_CGAPNRC_INFO_IND_STRU)= 0x28,
	MSG_SHOW_NAME(D_EPS_ACTIVE_IND,							LNB_EPS_ACTIVE_IND_STRU)= 0x29,
	MSG_SHOW_NAME(D_EPS_UICCID_CNF,							MSG_HEADER_STRU)= 0x2a,

	MSG_SHOW_NAME(D_EPS_REG_STATUS_IND,						LNB_REG_STATUS_IND_STRU)= 0x2b,
	MSG_SHOW_NAME(D_EPS_SIGNAL_CONN_STATUS_IND,				LNB_SIGNAL_CONN_STATUS_IND_STRU)= 0x2c,
	MSG_SHOW_NAME(D_EPS_EDRX_PARA_CHANGE_IND,				LNB_EDRX_PARA_CHANGE_IND_STRU)= 0x2d,
	MSG_SHOW_NAME(D_EPS_CSODCP_ABORT_CNF,					LNB_CSODCP_ABORT_CNF_STRU)= 0x2e,
	MSG_SHOW_NAME(D_EPS_CCIOTOPT_REPORT_IND,				MSG_HEADER_STRU)= 0x2f,

	MSG_SHOW_NAME(D_EPS_UICC_ID_REQ,						LNB_EPS_UICC_ID_REQ_STRU) 				= 0x30, 
	MSG_SHOW_NAME(D_EPS_CSODCP_ABORT_REQ,					LNB_EPS_CSODCP_ABORT_REQ_STRU) 			= 0x31, 	
	MSG_SHOW_NAME(D_EPS_CCIOTOPT_SET_REQ,					LNB_EPS_CCIOTOPT_SET_REQ_STRU) 			= 0x32, 	
	MSG_SHOW_NAME(D_EPS_PDN_IPDNS_IND,					    LNB_PDN_IPDNS_IND_STRU)                 = 0x33,
}ATC_NAS_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(D_ATC_DATA_REQ,							ST_ATC_DATA_REQ_LOG) = 0x00,
	MSG_SHOW_NAME(D_ATC_DATA_IND,							ST_ATC_DATA_IND) = 0x01,
	MSG_SHOW_NAME(D_ATC_ATO_IND,							ST_ATC_ATO_IND) = 0x03,
	MSG_SHOW_NAME(D_ATC_UPLANE_START_IND,					MSG_HEADER_STRU) = 0x05,
	MSG_SHOW_NAME(D_ATC_UPLANE_STOP_IND,					MSG_HEADER_STRU) = 0x07,
	MSG_SHOW_NAME(D_ATC_PS_PROGRESS_IND,					MSG_HEADER_STRU) = 0x7F,
	MSG_SHOW_NAME(D_EPS_USER_DATA_REQ,						LNB_USER_DATA_REQ_STRU) = 0x11,	
	MSG_SHOW_NAME(D_EPS_USER_DATA_IND,						MSG_HEADER_STRU) = 0x12,
	MSG_SHOW_NAME(D_EPS_APL_DATA_SEND_REQ,					LNB_EPS_APL_DATA_SEND_REQ_STRU) = 0x13,
	MSG_SHOW_NAME(START_UART_DATA,							START_UART_DATA_STRU) = 0x21,
	MSG_SHOW_NAME(STOP_UART_DATA,							STOP_UART_DATA_STRU) = 0x22,
	MSG_SHOW_NAME(START_APL_DATA,							START_APL_DATA_STRU) = 0x25,
	MSG_SHOW_NAME(D_ATC_DATA_REQ_LONG_INFO, 				MSG_HEADER_STRU) = 0x26,

}APP_PS_AP_CLASS_E;


typedef enum
{
	MSG_SHOW_NAME(D_SMS_RL_DATA_REQ,						LNB_SMS_RL_DATA_REQ_STRU) = 0x00,
	MSG_SHOW_NAME(D_SMS_RL_REPORT_REQ,						LNB_SMS_RL_REPORT_REQ_STRU) = 0x01,
	MSG_SHOW_NAME(D_SMS_RL_DATA_IND,						LNB_SMS_RL_DATA_IND_STRU) = 0x10,
	MSG_SHOW_NAME(D_SMS_RL_REPORT_IND,						LNB_SMS_RL_REPORT_IND_STRU) = 0x11,

}ATC_SMS_AP_CLASS_E;

typedef enum
{
	MSG_SHOW_NAME(SECURITY_HDR_TYPE_PLAIN_NAS, 				ST_LTE_MSG_HEADER          ) = 0x0,
	MSG_SHOW_NAME(SECURITY_HDR_TYPE_INTEGRITY,              ST_LTE_MSG_HEADER                             ) = 0x1,
	MSG_SHOW_NAME(SECURITY_HDR_TYPE_INTEGRITY_AND_CIPHERED, ST_LTE_MSG_HEADER                             ) = 0x2,
	MSG_SHOW_NAME(SECURITY_HDR_TYPE_INTEGRITY_WITH_NEW_EPS_SECURITY_CONTEXT,ST_LTE_MSG_HEADER             ) = 0x3,
	MSG_SHOW_NAME(SECURITY_HDR_TYPE_INTEGRITY_AND_CIPHERED_WITH_NEW_EPS_SECURITY_CONTEXT,ST_LTE_MSG_HEADER) = 0x4,
	MSG_SHOW_NAME(SECURITY_HDR_TYPE_INTEGRITY_AND_PARTAILLY_CIPHERED_NAS_MESSAGE,  ST_LTE_MSG_HEADER      ) =0x5,
	MSG_SHOW_NAME(SECURITY_HDR_TYPE_SERVICE_REQUEST,                               ST_LTE_MSG_HEADER      ) = 0xC,
		
	/*****************************************************************************/
	/******************** EMM AIR MESSAGE'S PROTOCO DISCRIMINATOR*****************/
	/*****************************************************************************/
	MSG_SHOW_NAME(PD_EPS_SESSION_MANAGEMENT,                                      ST_LTE_BEARER_MSG_HEADER      ) =  0x2,
	MSG_SHOW_NAME(PD_EPS_MOBILITY_MANAGEMENT,                                      ST_LTE_MSG_HEADER     ) =  0x7,
	MSG_SHOW_NAME(PD_TC_MOBILITY_MANAGEMENT,                                        ST_LTE_MSG_HEADER    ) =   0xF,
	
	/*****************************************************************************/
	/**************************** EMM AIR MESSAGE'S MESSAGE_TYPE******************/
	/*****************************************************************************/
	MSG_SHOW_NAME( MESSAGE_TYPE_ATTACH_REQUEST,           ST_LTE_ATTACH_REQ      ) =0x41,
	MSG_SHOW_NAME( MESSAGE_TYPE_ATTACH_ACCEPT,             ST_LTE_ATTACH_ACCEPT      ) =0x42,
	MSG_SHOW_NAME( MESSAGE_TYPE_ATTACH_COMPLETE,           ST_LTE_ATTACH_COMPLETE     	) = 0x43,
	MSG_SHOW_NAME( MESSAGE_TYPE_ATTACH_REJECT,              ST_LTE_ATTACH_REJECT    	) = 0x44,
	MSG_SHOW_NAME( MESSAGE_TYPE_DETACH_REQUEST,              ST_LTE_DETACH_REQUEST_ORI    ) = 0x45,
	MSG_SHOW_NAME( MESSAGE_TYPE_DETACH_ACCEPT ,               ST_LTE_DETACH_ACCEPT_ORI   ) = 0x46,
	MSG_SHOW_NAME( MESSAGE_TYPE_TRACKING_AREA_UPDATE_REQUEST, ST_LTE_TRACKING_AREA_UPDATE_REQ   ) =0x48,
	MSG_SHOW_NAME( MESSAGE_TYPE_TRACKING_AREA_UPDATE_ACCEPT  , ST_LTE_TRACKING_AREA_UPDATE_ACCEPT  ) =0x49,
	MSG_SHOW_NAME( MESSAGE_TYPE_TRACKING_AREA_UPDATE_COMPLETE , ST_LTE_TAU_COMPLETE) = 0x4A,
	MSG_SHOW_NAME( MESSAGE_TYPE_TRACKING_AREA_UPDATE_REJECT,   ST_LTE_TRACKING_AREA_UPDATE_REJECT)=  0x4B,
	MSG_SHOW_NAME( MESSAGE_TYPE_EXTENDED_SERVICE_REQUEST,      ST_LTE_EXTENDED_SERVICE_REQ  ) =0x4C,
	MSG_SHOW_NAME( MESSAGE_TYPE_CP_SERVICE_REQUEST,            ST_LTE_SERVICE_REQ  ) =0x4D,
	MSG_SHOW_NAME( MESSAGE_TYPE_SERVICE_REJECT,                ST_LTE_SERV_REJECT  ) =0x4E,
	MSG_SHOW_NAME( MESSAGE_TYPE_SERVICE_ACCEPT,                ST_LTE_SERV_ACCEPT ) = 0x4F,
	MSG_SHOW_NAME( MESSAGE_TYPE_GUTI_REALLOCATION_COMMAND,     ST_LTE_GUTI_REALLOCATION_COMMAND ) =0x50,
	MSG_SHOW_NAME( MESSAGE_TYPE_GUTI_REALLOCATION_COMPLETE,    ST_LTE_GUTI_REALLOCATION_COMPLETE ) = 0x51,
	MSG_SHOW_NAME( MESSAGE_TYPE_AUTHENTICATION_REQUEST,        ST_LTE_AUTHENTICATION_REQUEST ) = 0x52,
	MSG_SHOW_NAME( MESSAGE_TYPE_AUTHENTICATION_RESPONSE,       ST_LTE_AUTHENTICATION_RESPONSE ) =  0x53,
	MSG_SHOW_NAME( MESSAGE_TYPE_AUTHENTICATION_REJECT,         ST_LTE_AUTHENTICATION_REJECT ) = 0x54,
	MSG_SHOW_NAME( MESSAGE_TYPE_AUTHENTICATION_FAILURE,       ST_AUTH_FAIL_IE ) =  0x5C,
	MSG_SHOW_NAME( MESSAGE_TYPE_IDENTITY_REQUEST,             ST_LTE_IDENTITY_REQUEST  ) = 0x55,
	MSG_SHOW_NAME( MESSAGE_TYPE_IDENTITY_RESPONSE,            ST_LTE_ID_RESPONSE ) =  0x56,
	MSG_SHOW_NAME( MESSAGE_TYPE_SECURITY_MODE_COMMAND,        ST_LTE_SECUR_MODE_COMMAND ) =  0x5D,
	MSG_SHOW_NAME( MESSAGE_TYPE_SECURITY_MODE_COMPLETE,       ST_LTE_MSG_SECUR_MODE_CMPL ) =  0x5E,
	MSG_SHOW_NAME( MESSAGE_TYPE_SECURITY_MODE_REJECT ,        ST_LTE_SECURITY_MODE_REJECT ) =  0x5F,
	MSG_SHOW_NAME( MESSAGE_TYPE_EMM_STATUS,                   ST_LTE_EMM_STATUS ) =  0x60,
	MSG_SHOW_NAME( MESSAGE_TYPE_EMM_INFORMATION,              ST_LTE_EMM_INFORMATION ) =  0x61,
	MSG_SHOW_NAME( MESSAGE_TYPE_DOWNLINK_NAS_TRANSPORT,       ST_LTE_DOWNLINK_NAS_TRANSPORT ) =  0x62,
	MSG_SHOW_NAME( MESSAGE_TYPE_UPLINK_NAS_TRANSPORT,         ST_LTE_UL_NAS_TRANSP ) =  0x63,
	MSG_SHOW_NAME( MESSAGE_TYPE_CS_SERVICE_NOTIFICATION,      ST_LTE_CS_SERVICE_NOTIFICATION ) =  0x64,
	MSG_SHOW_NAME( MESSAGE_TYPE_DOWNLINK_GENERIC_NAS_TRANSPORT,ST_LTE_DL_GENERIC_NAS_TRANSP) =  0x68,
	MSG_SHOW_NAME( MESSAGE_TYPE_UPLINK_GENERIC_NAS_TRANSPORT, ST_LTE_UL_GENERIC_NAS_TRANSP ) =  0x69,
		
	MSG_SHOW_NAME( MESSAGE_TYPE_CLOSE_UE_TEST_LOOP,            ST_LTC_CLOSE_UE_TEST_LOOP) =  0x80,
	MSG_SHOW_NAME( MESSAGE_TYPE_CLOSE_UE_TEST_LOOP_COMPLETE,   ST_LTC_CLOSE_UE_TEST_LOOP_COMPLETE) =  0x81,
	MSG_SHOW_NAME( MESSAGE_TYPE_OPEN_UE_TEST_LOOP,             ST_LTC_CLOSE_UE_TEST_LOOP) =  0x82,
	MSG_SHOW_NAME( MESSAGE_TYPE_OPEN_UE_TEST_LOOP_COMPLETE,    ST_LTC_OPEN_UE_TEST_LOOP_COMPLETE) =  0x83,
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVE_TEST_MODE,              ST_LTC_ACTIVATE_TEST_MODE) =  0x84,
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVE_TEST_MODE_COMPLETE,     ST_LTC_ACTIVATE_TEST_MODE_COMPLETE) =  0x85,
	MSG_SHOW_NAME( MESSAGE_TYPE_DEACTIVE_TEST_MODE,            ST_LTC_DEACTIVATE_TEST_MODE) =  0x86,
	MSG_SHOW_NAME( MESSAGE_TYPE_DEACTIVE_TEST_MODE_COMPLETE,  ST_LTC_DEACTIVATE_TEST_MODE_COMPLETE ) =  0x87,
		/*****************************************************************************/
		/**************************** ESM AIR MESSAGE'S MESSAGE_TYPE******************/
		/*****************************************************************************/
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST,    ST_LTE_MODIFY_EPS_BEARER_CONTEXT_REQ ) =  0xC1,
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT,     ST_LTE_MODIFY_EPS_BEARER_CONTEXT_ACCEPT ) =  0xC2,
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT,     ST_LTE_MODIFY_EPS_BEARER_CONTEXT_REJECT ) =  0xC3,
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST,  ST_LTE_ACTIVATE_DDCTD_EPS_BEARER_CONTEXT_REQ ) =  0xC5,
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT,   ST_LTE_ACTIVATE_DDCTD_EPS_BEARER_CONTEXT_ACCEPT  ) = 0xC6,
	MSG_SHOW_NAME( MESSAGE_TYPE_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT,    ST_LTE_ACTIVATE_DDCTD_EPS_BEARER_CONTEXT_REJECT ) = 0xC7,
	MSG_SHOW_NAME( MESSAGE_TYPE_MODIFY_EPS_BEARER_CONTEXT_REQUEST,               ST_LTE_MODIFY_EPS_BEARER_CONTEXT_REQ ) = 0xC9,
	MSG_SHOW_NAME( MESSAGE_TYPE_MODIFY_EPS_BEARER_CONTEXT_ACCEPT,                ST_LTE_MODIFY_EPS_BEARER_CONTEXT_ACCEPT ) = 0xCA,
	MSG_SHOW_NAME( MESSAGE_TYPE_MODIFY_EPS_BEARER_CONTEXT_REJECT,                ST_LTE_MODIFY_EPS_BEARER_CONTEXT_REJECT ) = 0xCB,
	MSG_SHOW_NAME( MESSAGE_TYPE_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST ,         ST_LTE_DEACTIVATE_EPS_BEARER_CONTEXT_REQ  ) = 0xCD,
	MSG_SHOW_NAME( MESSAGE_TYPE_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT ,          ST_LTE_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT  ) = 0xCE,
	MSG_SHOW_NAME( MESSAGE_TYPE_PDN_CONNECTIVITY_REQUEST,                       ST_LTE_PDN_CONNECTIVITY_REQ  ) = 0xD0,
	MSG_SHOW_NAME( MESSAGE_TYPE_PDN_CONNECTIVITY_REJECT ,                       ST_LTE_PDN_CONNECTIVITY_REJECT  ) = 0xD1,
	MSG_SHOW_NAME( MESSAGE_TYPE_PDN_DISCONNECT_REQUEST ,                        ST_LTE_PDN_DISCONNECT_REQ  ) = 0xD2,
	MSG_SHOW_NAME( MESSAGE_TYPE_PDN_DISCONNECT_REJECT ,                         ST_LTE_PDN_DISCONNECT_REJECT  ) = 0xD3,
	MSG_SHOW_NAME( MESSAGE_TYPE_BEARER_RESOURCE_ALLOCATION_REQUEST,             ST_LTE_BEARER_RESOURCE_ALLOC_REQ  ) = 0xD4,
	MSG_SHOW_NAME( MESSAGE_TYPE_BEARER_RESOURCE_ALLOCATION_REJECT ,             ST_LTE_BEARER_RESOURCE_ALLOC_REJECT  ) = 0xD5,
	MSG_SHOW_NAME( MESSAGE_TYPE_BEARER_RESOURCE_MODIFICATION_REQUEST,            ST_LTE_BEARER_RESOURCE_MODIFICATION_REQ ) = 0xD6,
	MSG_SHOW_NAME( MESSAGE_TYPE_BEARER_RESOURCE_MODIFICATION_REJECT,             ST_LTE_BEARER_RESOURCE_MODIFICATION_REJECT ) = 0xD7,
	MSG_SHOW_NAME( MESSAGE_TYPE_ESM_INFORMATION_REQUEST,                         ST_LTE_ESM_INFO_REQ ) = 0xD9,
	MSG_SHOW_NAME( MESSAGE_TYPE_ESM_INFORMATION_RESPONSE,                        ST_LTE_ESM_INFO_RESPONSE ) = 0xDA,
	MSG_SHOW_NAME( MESSAGE_TYPE_NOTIFICATION ,                                   ST_LTE_NOTIFICATION_IE ) = 0xDB,
	MSG_SHOW_NAME( MESSAGE_TYPE_ESM_DUMMY_MESSAGE ,                              ST_LTE_ESM_DUMMY_MSG ) = 0xDC,
	MSG_SHOW_NAME( MESSAGE_TYPE_ESM_STATUS,                                      ST_LTE_ESM_STA ) = 0xE8,
	MSG_SHOW_NAME( MESSAGE_TYPE_REMOTE_UE_REPORT ,                              REMOTE_UE_REPORT_RSP  ) = 0xE9,
	MSG_SHOW_NAME( MESSAGE_TYPE_REMOTE_UE_REPORT_RESPONSE ,                     REMOTE_UE_REPORT_RSP  ) = 0xEA,
	MSG_SHOW_NAME( MESSAGE_TYPE_ESM_DATA_TRANSPORT,                             ST_LTE_ESM_DATA_TRANSP  ) = 0xEB,
	MSG_SHOW_NAME( LNB_Security_protected_NAS_message_STATIC,                   MSG_HEADER_STRU  ) =  0xEC,
	MSG_SHOW_NAME( LNB_Service_request_STATIC,                                  ST_LTE_SERVICE_REQ  ) =  0xED,
}NA_MSG_E;

#endif


