#ifndef NBIOT_MODUL_HEADER
#define NBIOT_MODUL_HEADER
#include "softap_macro.h"
#define ENUM_SHOW_NAME(id, name) id
typedef enum
{   
    ENUM_SHOW_NAME(L2_THREAD_ID, L2)	     = 0,
  	ENUM_SHOW_NAME(NAS_THREAD_ID, NAS)		 = 1,  	
    ENUM_SHOW_NAME(LNBPS_MAX_THREAD, LNBPS)  = 2,

 	ENUM_SHOW_NAME(ADMIN_THREAD_ID, ADMIN)   = LNBPS_MAX_THREAD,
	ENUM_SHOW_NAME(LPHY_THREAD_ID, LPHY)     = LNBPS_MAX_THREAD+1,
	ENUM_SHOW_NAME(LRRC_THREAD_ID, LRRC)	 = LNBPS_MAX_THREAD+2,
	ENUM_SHOW_NAME(UART_THREAD_ID, UART)	 = LNBPS_MAX_THREAD+3,

	ENUM_SHOW_NAME(OM_THREAD_ID, OM)  		 = LNBPS_MAX_THREAD+4,
    ENUM_SHOW_NAME(BIP_THREAD_ID, BIP)       = LNBPS_MAX_THREAD+5,
	ENUM_SHOW_NAME(ULRLC_THREAD_ID, L2)  	 = L2_THREAD_ID,
	ENUM_SHOW_NAME(DLRLC_THREAD_ID, L2)  	 = L2_THREAD_ID,
	ENUM_SHOW_NAME(ULMAC_THREAD_ID, L2)  	 = L2_THREAD_ID,
	ENUM_SHOW_NAME(DLMAC_THREAD_ID, L2)  	 = L2_THREAD_ID,
	ENUM_SHOW_NAME(LPDCP_THREAD_ID, LRRC)    = LRRC_THREAD_ID,
	ENUM_SHOW_NAME(USIM_THREAD_ID, NAS)      = NAS_THREAD_ID,
	ENUM_SHOW_NAME(ATC_THREAD_ID, NAS) 	 	 = NAS_THREAD_ID,
	ENUM_SHOW_NAME(RABM_THREAD_ID, RABM)	 = 14,

	MAX_MODULE_ID = 50,
}NBIOT_THREAD_E;

typedef enum
{
	DEBUG_LOG,
	INFO_LOG,
	WARN_LOG,
	FATAL_LOG,
	CRITICAL_LOG,
	MAX_LEV_LOG,
}XY_LOG_LEV;

typedef enum
{
    LAYER2	= 0,
    NAS		= 1,
    ADMIN   = 2,
    LPHY    = 3,
    LRRC    = 4,
    UART    = 5,
    LNBPS   = 6,
    PCTOOL  = 7,
    L1C     = 8,
    WIRESHARCK = 9,
    PLATFORM   = 10,
    ATCTRL     = 11,
    WIRESHARCK_M3 = 12,
    PLATFORM_M3   = 13,
    ATCTRL_M3     = 14,
    USER_LOG      = 15,
    BIP           = 16,
    XYLOG_MAX_BLOCK,
}XY_SRC_E;

#endif

